### ISSUE TITLE
Get input-hours and input-minutes?!

### ISSUE THREAD

**Issue by ahmad-atallah** [mtrdesign/mtr-datepicker#10]
@valkirilov is there's anyway to get the values of the mtr-datepicker after the user change it??
I tried doing: 
`var hours = document.getElementById('mtr-datepicker-input-hours').value;`

but it didn't work! any ideas?!

**Comment by valkirilov** [comment]
Hi @ahmad-atallah,

Your approach is incorrect, you don't have to get the values from the DOM, use the provided API instead:
http://mtrdesign.github.io/mtr-datepicker/docs.html#api-output-format

You can format the output so you can get only the hours value (like your example). 

But if this is not what you are looking for, we support events too so you can bind some behavior to the onChange event and it will be executed when the user change the values of the datepicker:
http://mtrdesign.github.io/mtr-datepicker/docs.html#api-events-on-change

**Comment by ahmad-atallah** [comment]
@valkirilov Thank you so much for your quick reply!!

I already tried the following but didn't work..

```
 var myDatepicker = document.getElementById('mtr-datepicker');
//OR: var myDatepicker = $("#mtr-datepicker");
var hours = myDatepicker.format('hh');
var minutes = myDatepicker.format('mm');

```
It's giving this error

> Uncaught TypeError: myDatepicker.format is not a function

**Comment by valkirilov** [comment]
You are trying to call the function on the DOM element, that's why you have the error.

Instead, you should call the function on the instance of the datepicker:

```
<script>
  var config = {
    target: 'mtr-datepicker',
  };
  var myDatepicker = new MtrDatepicker(config);
  var datepickerOutput = myDatepicker.format('D.M.Y h:m A');

  console.log(datepickerOutput);
</script>
```

**Comment by ahmad-atallah** [comment]
So how in your example I will use `datepickerOutput` **after** the user changes the time?
Or it must be done through `onChange` event? I'm trying it now anyway..

**Comment by ahmad-atallah** [comment]
Yep, `onChange` did the trick.. Thank you again for your quick reply, and for the amazing tool..

**Comment by valkirilov** [comment]
Great, I'm glad that I helped you :)
