### ISSUE TITLE
Change date by typing it in

### ISSUE THREAD

**Issue by lguariento** [mtrdesign/mtr-datepicker#11]
Is it possible to change the date by just typing it in by hand, and get the value to be updated when hitting 'return' or changing focus? Right now if I change the date (say, the day) and hit 'enter' nothing happens. I have a button which grabs, via javaScript, the date via a `mypicker.format('YYYY-MM-DD')`; If I press the button after having changed the day value, the selected day is still the old one. I have to click somewhere on the page to finally have the picker 'recognise' the value I want.

**Comment by lguariento** [comment]
Thanks @valkirilov

**Comment by valkirilov** [comment]
@lguariento, the feature is implemented and available in the latest release of the datepicker (v0.3.11).
