### ISSUE TITLE
Mtr-datepicker does not contain information about afterChange().

### ISSUE THREAD

**Issue by SMKim94** [mtrdesign/mtr-datepicker#12]
I saw afterChange() method in mtr-datepicker.js. 
But Mtr-datepicker document does not contain information about afterChange() method. 

When I used the method, It works.

**Comment by valkirilov** [comment]
Hi @SMKim94 ,

the docs contains info and a simple snippet how to use the `onChange` event, you can refer to them:
http://mtrdesign.github.io/mtr-datepicker/docs.html#api-events-on-change
