### ISSUE TITLE
Time is missing leading zero

### ISSUE THREAD

**Issue by SLCPS** [mtrdesign/mtr-datepicker#17]
Time is missing the leading zero if you set it for less than 10 minute increments in some cases.
![time](https://user-images.githubusercontent.com/25752117/70275471-31f8e480-177c-11ea-8c34-21781eb6efeb.JPG)

**Comment by valkirilov** [comment]
Hi @SLCPS,

it looks more like a non-implemented feature rather than a bug.
Thank you for reporting it.

**Comment by valkirilov** [comment]
Hi @SLCPS ,

the bug is fixed in the newest version of the datepicker (v0.3.11).
