### ISSUE TITLE
Time only?

### ISSUE THREAD

**Issue by SLCPS** [mtrdesign/mtr-datepicker#18]
Maybe I'm blind, but is there an option to do just time and no date?

**Comment by valkirilov** [comment]
Hi @SLCPS,

currently such behavior is not supported by default. We'll consider it in our future plans.
For now you can simply workaround it with some custom JS/CSS by hiding the `.mtr-row` with the date controls.

**Comment by valkirilov** [comment]
Finally we can introduce this feature as implemented and ready to use. Now you can use to config the control the visibility of the date/time picker areas, it's a simple boolean switch and it's described in the [docs](http://mtrdesign.github.io/mtr-datepicker/docs.html#api-init-disable-datepicker). The changes are part of the latest released version [0.3.10](https://github.com/mtrdesign/mtr-datepicker/releases/tag/v0.3.10).
