### ISSUE TITLE
When we enter day with a leading Zero like "01", slider gets messed up

### ISSUE THREAD

**Issue by accessallow** [mtrdesign/mtr-datepicker#23]
![Leading Zero Date](https://user-images.githubusercontent.com/5000086/77820395-0c676080-7108-11ea-9e87-621155105260.png)
![Observation](https://user-images.githubusercontent.com/5000086/77820397-11c4ab00-7108-11ea-854a-e117bc74310e.png)

We were able to fix this bug by modifying function **updateInputSlider**

We added a new function **sanitizeValue**  and called it to sanitize the leading zero input before further processing into **updateInputSlider**.

![image](https://user-images.githubusercontent.com/5000086/77820462-85ff4e80-7108-11ea-9faa-792de91c2c84.png)

Kindly accept the bug fix. We stumbled upon it when working on a bug fix in our code.

**Regards**
Pankaj Tiwari (https://github.com/accessallow)
Kaushamb Tiwari (https://github.com/kaushamb)

**Comment by valkirilov** [comment]
The bug has been fixed and is part of our latest release [v0.3.10](https://github.com/mtrdesign/mtr-datepicker/releases/tag/v0.3.10). You can now safely input values with leading zeroes without braking the UI.
