### ISSUE TITLE
Publish NPM package?

### ISSUE THREAD

**Issue by neokio** [mtrdesign/mtr-datepicker#4]
You have a Bower package published, which is great, but would you consider publishing via NPM as well?

**Comment by valkirilov** [comment]
Hi @neokio,

the NPM package of the datepicker is published in NPM - [https://www.npmjs.com/package/mtr-datepicker](https://www.npmjs.com/package/mtr-datepicker). 
You can download it in your projects with the following command:

```
npm install --save mtr-datepicker
```

**Comment by neokio** [comment]
Much appreciated!
