### ISSUE TITLE
smartHours sticks on PM

### ISSUE THREAD

**Issue by skwny** [mtrdesign/mtr-datepicker#5]
When going from '11' to '12' in the Hours column, smartHours will automatically set to 'p.m'. However, attempting to select 'a.m' is impossible until changing a date value. 

Also, going backwards will not engage smartHours to change back to 'a.m' once 'p.m.' has been selected.

**Comment by valkirilov** [comment]
Hi @skwny,

> When going from '11' to '12' in the Hours column, smartHours will automatically set to 'p.m'. However, attempting to select 'a.m' is impossible until changing a date value.

Can you provide your `config` which you pass to the datepicker?

**Comment by skwny** [comment]
var config = {
      future: true,
      smartHours: true,
      target: 'first-mtr-datepicker'
};

**Comment by valkirilov** [comment]
Hi @skwny,

the behavior of the `smartHours` feature is now even smarter in the latest release of the lib (v0.3.7). I mean that now when you go from 12PM to 11, the datepicker automatically switches back to AM, as you requested.

I hope that you'll like the latest update and continue to use MTR Datepicker in your future projects, thank you! :)
